---
- name: Testing 1st playbook 
  hosts: all 
  tasks: 
    - name: Restarting SSHD 
      service: 
        name: sshd 
        state: restarted
      
      name: Restart ntpd  
      service:
        name: ntpd 
        state: restarted
...           
